// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.2
// source: nexus/v1/streaming.proto

package nexusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CompletionsClient is the client API for Completions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompletionsClient interface {
	CompleteStream(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (Completions_CompleteStreamClient, error)
}

type completionsClient struct {
	cc grpc.ClientConnInterface
}

func NewCompletionsClient(cc grpc.ClientConnInterface) CompletionsClient {
	return &completionsClient{cc}
}

func (c *completionsClient) CompleteStream(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (Completions_CompleteStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Completions_ServiceDesc.Streams[0], "/nexus.v1.Completions/CompleteStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &completionsCompleteStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Completions_CompleteStreamClient interface {
	Recv() (*StreamEvent, error)
	grpc.ClientStream
}

type completionsCompleteStreamClient struct {
	grpc.ClientStream
}

func (x *completionsCompleteStreamClient) Recv() (*StreamEvent, error) {
	m := new(StreamEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CompletionsServer is the server API for Completions service.
// All implementations must embed UnimplementedCompletionsServer
// for forward compatibility
type CompletionsServer interface {
	CompleteStream(*CompletionRequest, Completions_CompleteStreamServer) error
	mustEmbedUnimplementedCompletionsServer()
}

// UnimplementedCompletionsServer must be embedded to have forward compatible implementations.
type UnimplementedCompletionsServer struct {
}

func (UnimplementedCompletionsServer) CompleteStream(*CompletionRequest, Completions_CompleteStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CompleteStream not implemented")
}
func (UnimplementedCompletionsServer) mustEmbedUnimplementedCompletionsServer() {}

// UnsafeCompletionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompletionsServer will
// result in compilation errors.
type UnsafeCompletionsServer interface {
	mustEmbedUnimplementedCompletionsServer()
}

func RegisterCompletionsServer(s grpc.ServiceRegistrar, srv CompletionsServer) {
	s.RegisterService(&Completions_ServiceDesc, srv)
}

func _Completions_CompleteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CompletionsServer).CompleteStream(m, &completionsCompleteStreamServer{stream})
}

type Completions_CompleteStreamServer interface {
	Send(*StreamEvent) error
	grpc.ServerStream
}

type completionsCompleteStreamServer struct {
	grpc.ServerStream
}

func (x *completionsCompleteStreamServer) Send(m *StreamEvent) error {
	return x.ServerStream.SendMsg(m)
}

// Completions_ServiceDesc is the grpc.ServiceDesc for Completions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Completions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.v1.Completions",
	HandlerType: (*CompletionsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CompleteStream",
			Handler:       _Completions_CompleteStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nexus/v1/streaming.proto",
}
